In [61]:
import pandas as pd
from sklearn.model_selection import train_test_split
import pickle
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [62]:
##load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [63]:
##preprocess the data
##drop irrelevant columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [64]:
##encode categorical features
from sklearn.preprocessing import LabelEncoder

label_encoder_gender = LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [65]:
##onehot encode geography
from sklearn.preprocessing import OneHotEncoder

onehot_encoder_geo = OneHotEncoder(sparse_output=False)

geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [66]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [67]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [68]:
##save the encoders and scalers
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
    
with open ('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [69]:
X=data.drop(['Exited'],axis=1)
Y=data['Exited']

In [70]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [71]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [72]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [73]:
 pip install tensorflow==2.21.0

Requirement already satisfied: tensorflow==2.21.0 in c:\users\tejus\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (2.5.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (3.4.0)
Requirement already satisfied: packaging in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (7.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (2.32.5)
Requirement already satisfied: setuptools in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (1.84.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (2.3.5)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\tejus\anaconda3\lib\site-packages (from tensorflow==2.21.0) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\tejus\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tejus\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\tejus\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tejus\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (2026.1.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\tejus\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow==2.21.0) (0.45.1)
Requirement already satisfied: rich in c:\users\tejus\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow==2.21.0) (14.2.0)
Requirement already satisfied: namex in c:\users\tejus\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow==2.21.0) (0.1.0)
Requirement already satisfied: optree in c:\users\tejus\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow==2.21.0) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\tejus\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow==2.21.0) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\tejus\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow==2.21.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\tejus\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow==2.21.0) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [74]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [75]:
(x_train.shape[1],)

(12,)

In [76]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),##hl1 connected with input layer
    Dense(32, activation='relu'),##hl2
    Dense(1, activation='sigmoid')##output layer
])

c:\Users\Tejus\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [77]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [78]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [79]:
##compile the model

model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [80]:
##setup the tensorboard
import datetime
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [81]:
##setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [82]:
pip install TensorBoard

Requirement already satisfied: TensorBoard in c:\users\tejus\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (2.5.1)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (1.84.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (3.8)
Requirement already satisfied: numpy>=1.12.0 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (2.3.5)
Requirement already satisfied: packaging in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (25.0)
Requirement already satisfied: pillow in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (12.0.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (7.36.2)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (80.9.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\tejus\anaconda3\lib\site-packages (from TensorBoard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\tejus\anaconda3\lib\site-packages (from grpcio<2.0,>=1.74.0->TensorBoard) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\tejus\anaconda3\lib\site-packages (from werkzeug>=1.0.1->TensorBoard) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [83]:
##train the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8381 - loss: 0.3940 - val_accuracy: 0.8450 - val_loss: 0.3736
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8537 - loss: 0.3597 - val_accuracy: 0.8550 - val_loss: 0.3614
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8572 - loss: 0.3496 - val_accuracy: 0.8585 - val_loss: 0.3444
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8580 - loss: 0.3455 - val_accuracy: 0.8640 - val_loss: 0.3405
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8630 - loss: 0.3438 - val_accuracy: 0.8625 - val_loss: 0.3395
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8609 - loss: 0.3376 - val_accuracy: 0.8530 - val_loss: 0.3524
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8619 - loss: 0.3405 - val_accuracy: 0.8595 - val_loss: 0.3385
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8624 - loss: 0.3346 - val_accuracy: 0.8480 - val_loss: 0.3577
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8662 - loss: 0.3320 - val_accuracy: 0.8585 - val_loss: 0.3468
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8631 - loss: 0.3321 - val_accuracy: 0.8570 - val_loss: 0.3658
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8673 - loss: 0.3302 - val_accuracy: 0.8545 - val_loss: 0.3583
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8690 - loss: 0.3256 - val_accuracy: 0.8560 - val_loss: 0.3612
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8701 - loss: 0.3237 - val_accuracy: 0.8540 - val_loss: 0.3533
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8701 - loss: 0.3205 - val_accuracy: 0.8560 - val_loss: 0.3535
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8709 - loss: 0.3181 - val_accuracy: 0.8550 - val_loss: 0.3673
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8699 - loss: 0.3171 - val_accuracy: 0.8525 - val_loss: 0.3610
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8716 - loss: 0.3141 - val_accuracy: 0.8535 - val_loss: 0.3590

In [84]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [85]:
##load Tensorboard extensions
import tensorboard
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 1764), started 0:03:03 ago. (Use '!kill 1764' to kill it.)